[workspace]
resolver = "2"
members = [
  "core/rs-internal",
  "core/rs-macros",
  "core/rs",
  "http-lib/lib",
  "http-lib/core",
  "http-lib/target-info",
  "http-lib/direct-connector",
]


[workspace.package]
license = "AGPL-3.0-only"

[workspace.dependencies]
rustix = { version = "1.1.4", features = ["fs"] }
uuid = { version = "1.8.0", features = ["serde"] }
phf = { version = "0.11.2", features = ["macros"] }
hex-literal = "1.1.0"
const-hex = "1.11.3"
thiserror = "2.0.18"
anyhow = "1.0.95"
tracing = { version = "0.1.41", features = ["valuable"] }
valuable = { version = "0.1.1", features = ["derive"] }
indicatif = "0.18.4"
tracing-indicatif = "0.3.9"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = [
  "preserve_order",
  "float_roundtrip",
] }
http = "1.2.0"
reqwest = { version = "0.13.3", default-features = false, features = [
  "http2",
  "rustls",
  "query",
  "gzip",
  "deflate",
] }
tar = "0.4.43"
clap = { version = "4.6.1", features = ["derive", "env"] }
tokio = "1.43.0"
webar-core = { path = "./core/rs" }
