[package]
name = "webar-net-pktcap-conn"
description = "webar connector with packet captured"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
thiserror.workspace = true
snafu.workspace = true
tracing.workspace = true
pin-project.workspace = true
rustix = { workspace = true, features = ["net", "thread", "process", "event"] }
tokio = { workspace = true, features = ["net", "sync", "rt"] }
webar-core.workspace = true

[dev-dependencies]
rustix = { workspace = true, features = ["runtime"] }
tokio = { workspace = true, features = ["io-util"] }
temp-dir = "0.2.0"

[[test]]
name = "tcp-loopback"
harness = false
