[package]
name = "webar-core-internal"
version = "0.1.0"
edition = "2021"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icu_normalizer = "1.5.0"
icu_properties = "1.5.1"
