[package]
name = "webar-http-lib-core"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
anyhow.workspace = true
rustix.workspace = true
const-hex.workspace = true
rusqlite = "0.33.0"
webar-core.workspace = true
