[package]
name = "webar-http-fetcher-cli"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
rustix.workspace = true
webar-core.workspace = true
webar-utils-fs.workspace = true
webar-store-backend-fs.workspace = true
webar-http-lib-core = { path = "../core" }
